In [1]:
# Naive bayes:-- it is based on a probability

In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [23]:
d1=sns.load_dataset("tips")
d1

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [24]:
d1.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [25]:
d1.tail()

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [26]:
d1.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [27]:
d1.size

1708

In [28]:
d1.shape

(244, 7)

In [29]:
d1.isnull()

     total_bill    tip    sex  smoker    day   time   size
0         False  False  False   False  False  False  False
1         False  False  False   False  False  False  False
2         False  False  False   False  False  False  False
3         False  False  False   False  False  False  False
4         False  False  False   False  False  False  False
..          ...    ...    ...     ...    ...    ...    ...
239       False  False  False   False  False  False  False
240       False  False  False   False  False  False  False
241       False  False  False   False  False  False  False
242       False  False  False   False  False  False  False
243       False  False  False   False  False  False  False

[244 rows x 7 columns]

In [30]:
d1.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
239    False
240    False
241    False
242    False
243    False
Length: 244, dtype: bool

In [31]:
print(d1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB
None

In [32]:
print(d1.describe())

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [33]:
d1

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [34]:
# drop

In [35]:
d1=d1.drop(columns=['smoker','day'],axis=1)
d1

     total_bill   tip     sex    time  size
0         16.99  1.01  Female  Dinner     2
1         10.34  1.66    Male  Dinner     3
2         21.01  3.50    Male  Dinner     3
3         23.68  3.31    Male  Dinner     2
4         24.59  3.61  Female  Dinner     4
..          ...   ...     ...     ...   ...
239       29.03  5.92    Male  Dinner     3
240       27.18  2.00  Female  Dinner     2
241       22.67  2.00    Male  Dinner     2
242       17.82  1.75    Male  Dinner     2
243       18.78  3.00  Female  Dinner     2

[244 rows x 5 columns]

In [36]:
# Feature encoding:--

d1['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [37]:
d1['time']=d1['time'].map({'Dinner':0,'Lunch':1})
d1

     total_bill   tip     sex time  size
0         16.99  1.01  Female    0     2
1         10.34  1.66    Male    0     3
2         21.01  3.50    Male    0     3
3         23.68  3.31    Male    0     2
4         24.59  3.61  Female    0     4
..          ...   ...     ...  ...   ...
239       29.03  5.92    Male    0     3
240       27.18  2.00  Female    0     2
241       22.67  2.00    Male    0     2
242       17.82  1.75    Male    0     2
243       18.78  3.00  Female    0     2

[244 rows x 5 columns]

In [38]:
from sklearn.preprocessing import LabelEncoder
label=LabelEncoder()

In [40]:
d1['sex']=label.fit_transform(d1['sex'])
d1

     total_bill   tip  sex time  size
0         16.99  1.01    0    0     2
1         10.34  1.66    1    0     3
2         21.01  3.50    1    0     3
3         23.68  3.31    1    0     2
4         24.59  3.61    0    0     4
..          ...   ...  ...  ...   ...
239       29.03  5.92    1    0     3
240       27.18  2.00    0    0     2
241       22.67  2.00    1    0     2
242       17.82  1.75    1    0     2
243       18.78  3.00    0    0     2

[244 rows x 5 columns]

In [48]:
x=d1.drop('total_bill',axis=1)
y=d1['total_bill']

In [50]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.9)

In [56]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [58]:
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)

In [59]:
from sklearn.naive_bayes import GaussianNB

In [63]:
model=GaussianNB()
model.fit(x_train_scaled,y_train)

GaussianNB()

In [64]:
y_pred=model.predict(x_test_scaled)
y_pred

array([15, 18, 18, 23, 17, 18, 18, 18, 18, 17, 13, 13, 18, 23, 17, 17, 23,
       18, 18, 18, 23, 11, 13, 18, 15, 11, 11, 13, 11, 18, 11, 11, 23, 18,
       15, 23, 18, 15, 11, 17, 13, 11, 15, 15, 16, 23, 13, 11, 23, 15, 17,
       17, 18, 15, 18, 18, 17, 18, 18, 15, 17, 15, 15, 18, 17, 18, 26, 16,
       17, 18, 18, 17, 22, 18, 26, 22, 18, 18, 15, 15, 18, 18, 18, 15, 16,
       23, 18, 18, 13, 15, 26, 18, 18, 15, 18, 15, 26, 26, 17, 17, 23, 18,
       17, 13, 26, 18, 18, 11, 16, 11, 17, 26, 11, 16, 18, 18, 17, 11, 13,
       17, 18, 13, 15, 17, 26, 15, 17, 22, 18, 18, 18, 15, 26, 18, 13, 18,
       16, 16, 11, 18, 18, 17, 15, 15, 18, 18, 15, 23, 15, 17, 23, 18, 18,
       15, 26, 17, 15, 15, 18, 16, 26, 26, 23, 11, 11, 43, 26, 15, 15, 18,
       18, 15, 26, 18, 18, 15, 13, 15, 11, 18, 17, 13, 18, 18, 16, 23, 35,
       18, 18, 17, 26, 18, 11, 18, 17, 15, 26, 15, 17, 18, 18, 11, 26, 18,
       18, 26, 26, 23, 18, 18, 18, 17, 18, 26, 11, 15, 18, 34, 18, 17])

In [66]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_pred,y_test))

0.04090909090909091