In [2]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings # used to avoid the warning
warnings.filterwarnings("ignore")

In [3]:
df=pd.read_csv("insurance.csv")
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

Preprocessing

In [4]:
df_cleaned=df.copy()

In [5]:
print(df_cleaned.dtypes)

age           int64
sex          object
bmi         float64
children      int64
smoker       object
region       object
charges     float64
dtype: object

In [6]:
d2=df_cleaned["sex"].value_counts()
d2

sex
male      676
female    662
Name: count, dtype: int64

In [7]:
df_cleaned["sex"]=df_cleaned["sex"].map({"male":0,"female":1})
df_cleaned

      age  sex     bmi  children smoker     region      charges
0      19    1  27.900         0    yes  southwest  16884.92400
1      18    0  33.770         1     no  southeast   1725.55230
2      28    0  33.000         3     no  southeast   4449.46200
3      33    0  22.705         0     no  northwest  21984.47061
4      32    0  28.880         0     no  northwest   3866.85520
...   ...  ...     ...       ...    ...        ...          ...
1333   50    0  30.970         3     no  northwest  10600.54830
1334   18    1  31.920         0     no  northeast   2205.98080
1335   18    1  36.850         0     no  southeast   1629.83350
1336   21    1  25.800         0     no  southwest   2007.94500
1337   61    1  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [8]:
df_cleaned["smoker"].value_counts()

smoker
no     1064
yes     274
Name: count, dtype: int64

In [9]:
#label encoding:--
df_cleaned["smoker"]=df_cleaned["smoker"].map({"no":0,"yes":1})
df_cleaned

      age  sex     bmi  children  smoker     region      charges
0      19    1  27.900         0       1  southwest  16884.92400
1      18    0  33.770         1       0  southeast   1725.55230
2      28    0  33.000         3       0  southeast   4449.46200
3      33    0  22.705         0       0  northwest  21984.47061
4      32    0  28.880         0       0  northwest   3866.85520
...   ...  ...     ...       ...     ...        ...          ...
1333   50    0  30.970         3       0  northwest  10600.54830
1334   18    1  31.920         0       0  northeast   2205.98080
1335   18    1  36.850         0       0  southeast   1629.83350
1336   21    1  25.800         0       0  southwest   2007.94500
1337   61    1  29.070         0       1  northwest  29141.36030

[1338 rows x 7 columns]

In [10]:
df_cleaned.rename(columns=
                  {
                      "sex":"is_male",
                      "smoker":"is_smoker"
                  })

      age  is_male     bmi  children  is_smoker     region      charges
0      19        1  27.900         0          1  southwest  16884.92400
1      18        0  33.770         1          0  southeast   1725.55230
2      28        0  33.000         3          0  southeast   4449.46200
3      33        0  22.705         0          0  northwest  21984.47061
4      32        0  28.880         0          0  northwest   3866.85520
...   ...      ...     ...       ...        ...        ...          ...
1333   50        0  30.970         3          0  northwest  10600.54830
1334   18        1  31.920         0          0  northeast   2205.98080
1335   18        1  36.850         0          0  southeast   1629.83350
1336   21        1  25.800         0          0  southwest   2007.94500
1337   61        1  29.070         0          1  northwest  29141.36030

[1338 rows x 7 columns]

In [11]:
df_cleaned["region"].value_counts()

region
southeast    364
southwest    325
northwest    325
northeast    324
Name: count, dtype: int64