In [1]:
# Decision tree:-- It forms a tree like structure consists of a root ,leaf and branches

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

In [3]:
d1=pd.read_csv("insurance.csv")
d1

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [4]:
#EDA:--
print(d1.head(5))
print(d1.tail(5))

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520
      age     sex    bmi  children smoker     region     charges
1333   50    male  30.97         3     no  northwest  10600.5483
1334   18  female  31.92         0     no  northeast   2205.9808
1335   18  female  36.85         0     no  southeast   1629.8335
1336   21  female  25.80         0     no  southwest   2007.9450
1337   61  female  29.07         0    yes  northwest  29141.3603

In [5]:
print(d1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB
None

In [6]:
print(d1.describe())

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [7]:
print(d1.columns)

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

In [10]:
print(d1.isnull().sum())

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [11]:
print(d1.duplicated())

0       False
1       False
2       False
3       False
4       False
        ...
1333    False
1334    False
1335    False
1336    False
1337    False
Length: 1338, dtype: bool

In [12]:
print(d1.dropna())

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [13]:
# drop unwanted columns:--

In [16]:
d1=d1.drop(columns=['children','region','charges'],axis=1)

In [17]:
d1

      age     sex     bmi smoker
0      19  female  27.900    yes
1      18    male  33.770     no
2      28    male  33.000     no
3      33    male  22.705     no
4      32    male  28.880     no
...   ...     ...     ...    ...
1333   50    male  30.970     no
1334   18  female  31.920     no
1335   18  female  36.850     no
1336   21  female  25.800     no
1337   61  female  29.070    yes

[1338 rows x 4 columns]

In [ ]:
# Label encoding:--

In [18]:
d1['sex'].value_counts()

sex
male      676
female    662
Name: count, dtype: int64

In [19]:
d1['sex']=d1['sex'].map({'male':0,'female':1})

In [25]:
d1=d1.rename(columns={
    'sex':"ismale"
})
d1

      age  ismale     bmi smoker
0      19       1  27.900    yes
1      18       0  33.770     no
2      28       0  33.000     no
3      33       0  22.705     no
4      32       0  28.880     no
...   ...     ...     ...    ...
1333   50       0  30.970     no
1334   18       1  31.920     no
1335   18       1  36.850     no
1336   21       1  25.800     no
1337   61       1  29.070    yes

[1338 rows x 4 columns]

In [27]:
from sklearn.preprocessing import LabelEncoder
label=LabelEncoder()

In [29]:
d1['smoker']=label.fit_transform(d1['smoker'])
d1

      age  ismale     bmi  smoker
0      19       1  27.900       1
1      18       0  33.770       0
2      28       0  33.000       0
3      33       0  22.705       0
4      32       0  28.880       0
...   ...     ...     ...     ...
1333   50       0  30.970       0
1334   18       1  31.920       0
1335   18       1  36.850       0
1336   21       1  25.800       0
1337   61       1  29.070       1

[1338 rows x 4 columns]

In [30]:
print(d1.corr())

             age    ismale       bmi    smoker
age     1.000000  0.020856  0.109272 -0.025019
ismale  0.020856  1.000000 -0.046371 -0.076185
bmi     0.109272 -0.046371  1.000000  0.003750
smoker -0.025019 -0.076185  0.003750  1.000000

In [31]:
# model :--

In [33]:
x=d1.drop("smoker",axis=1)
y=d1["smoker"]

In [34]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.9)

In [44]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [45]:
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)

In [46]:
from sklearn.tree import DecisionTreeClassifier,plot_tree

In [47]:
model=DecisionTreeClassifier()
model

DecisionTreeClassifier()

In [48]:
model.fit(x_train_scaled,y_train)

DecisionTreeClassifier()

In [49]:
y_pred=model.predict(x_test_scaled)
y_pred

array([0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [50]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [51]:
print(accuracy_score(y_pred,y_test))

0.664179104477612

In [52]:
print(confusion_matrix(y_pred,y_test))

[[85 24]
 [21  4]]