In [1]:
import seaborn as sns
from sklearn.svm import SVC
import warnings
warnings.filterwarnings('ignore')

In [2]:
d1=sns.load_dataset('titanic')
d1

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [3]:

d1.isnull()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
887,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False
889,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False

In [4]:
d1.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [5]:
d1.dtypes

survived          int64
pclass            int64
sex              object
age             float64
sibsp             int64
parch             int64
fare            float64
embarked         object
class          category
who              object
adult_male         bool
deck           category
embark_town      object
alive            object
alone              bool
dtype: object

In [6]:
d1['age'].fillna(d1['age'].mean(),inplace=True)

In [7]:
d1

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.000000,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.000000,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.000000,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.000000,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.000000,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.000000,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.000000,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,29.699118,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.000000,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.000000,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [8]:
d1['age'].isnull().sum()

np.int64(0)

In [9]:
d1.isnull().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [10]:
d1['deck']="Y"

In [11]:
d1.loc[[2,3,4,5,6,7,8,8,9],'deck']=["S","C","C","Y","Y","A","R","P","Q"]

In [12]:
d1

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.000000,1,0,7.2500,S,Third,man,True,Y,Southampton,no,False
1,1,1,female,38.000000,1,0,71.2833,C,First,woman,False,Y,Cherbourg,yes,False
2,1,3,female,26.000000,0,0,7.9250,S,Third,woman,False,S,Southampton,yes,True
3,1,1,female,35.000000,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.000000,0,0,8.0500,S,Third,man,True,C,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.000000,0,0,13.0000,S,Second,man,True,Y,Southampton,no,True
887,1,1,female,19.000000,0,0,30.0000,S,First,woman,False,Y,Southampton,yes,True
888,0,3,female,29.699118,1,2,23.4500,S,Third,woman,False,Y,Southampton,no,False
889,1,1,male,26.000000,0,0,30.0000,C,First,man,True,Y,Cherbourg,yes,True
890,0,3,male,32.000000,0,0,7.7500,Q,Third,man,True,Y,Queenstown,no,True

In [13]:
d1=d1.dropna()

In [14]:
d1

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.000000,1,0,7.2500,S,Third,man,True,Y,Southampton,no,False
1,1,1,female,38.000000,1,0,71.2833,C,First,woman,False,Y,Cherbourg,yes,False
2,1,3,female,26.000000,0,0,7.9250,S,Third,woman,False,S,Southampton,yes,True
3,1,1,female,35.000000,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.000000,0,0,8.0500,S,Third,man,True,C,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.000000,0,0,13.0000,S,Second,man,True,Y,Southampton,no,True
887,1,1,female,19.000000,0,0,30.0000,S,First,woman,False,Y,Southampton,yes,True
888,0,3,female,29.699118,1,2,23.4500,S,Third,woman,False,Y,Southampton,no,False
889,1,1,male,26.000000,0,0,30.0000,C,First,man,True,Y,Cherbourg,yes,True
890,0,3,male,32.000000,0,0,7.7500,Q,Third,man,True,Y,Queenstown,no,True

In [15]:
x=d1.drop('survived',axis=1)
x

,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,3,male,22.000000,1,0,7.2500,S,Third,man,True,Y,Southampton,no,False
1,1,female,38.000000,1,0,71.2833,C,First,woman,False,Y,Cherbourg,yes,False
2,3,female,26.000000,0,0,7.9250,S,Third,woman,False,S,Southampton,yes,True
3,1,female,35.000000,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,3,male,35.000000,0,0,8.0500,S,Third,man,True,C,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,2,male,27.000000,0,0,13.0000,S,Second,man,True,Y,Southampton,no,True
887,1,female,19.000000,0,0,30.0000,S,First,woman,False,Y,Southampton,yes,True
888,3,female,29.699118,1,2,23.4500,S,Third,woman,False,Y,Southampton,no,False
889,1,male,26.000000,0,0,30.0000,C,First,man,True,Y,Cherbourg,yes,True
890,3,male,32.000000,0,0,7.7500,Q,Third,man,True,Y,Queenstown,no,True

In [16]:
y=d1[['survived']]
y

     survived
0           0
1           1
2           1
3           1
4           0
..        ...
886         0
887         1
888         0
889         1
890         0

[889 rows x 1 columns]

In [17]:
from sklearn.preprocessing import LabelEncoder
l_e=LabelEncoder()
cols=['sex','embarked','who','deck','embark_town','alive','class']
for l1 in cols:
    d1[l1]=l_e.fit_transform(d1[l1])

In [18]:
d1

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,1,22.000000,1,0,7.2500,2,2,1,True,5,2,0,False
1,1,1,0,38.000000,1,0,71.2833,0,0,2,False,5,0,1,False
2,1,3,0,26.000000,0,0,7.9250,2,2,2,False,4,2,1,True
3,1,1,0,35.000000,1,0,53.1000,2,0,2,False,1,2,1,False
4,0,3,1,35.000000,0,0,8.0500,2,2,1,True,1,2,0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,1,27.000000,0,0,13.0000,2,1,1,True,5,2,0,True
887,1,1,0,19.000000,0,0,30.0000,2,0,2,False,5,2,1,True
888,0,3,0,29.699118,1,2,23.4500,2,2,2,False,5,2,0,False
889,1,1,1,26.000000,0,0,30.0000,0,0,1,True,5,0,1,True
890,0,3,1,32.000000,0,0,7.7500,1,2,1,True,5,1,0,True

In [19]:
d1.astype(int)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,1,22,1,0,7,2,2,1,1,5,2,0,0
1,1,1,0,38,1,0,71,0,0,2,0,5,0,1,0
2,1,3,0,26,0,0,7,2,2,2,0,4,2,1,1
3,1,1,0,35,1,0,53,2,0,2,0,1,2,1,0
4,0,3,1,35,0,0,8,2,2,1,1,1,2,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,1,27,0,0,13,2,1,1,1,5,2,0,1
887,1,1,0,19,0,0,30,2,0,2,0,5,2,1,1
888,0,3,0,29,1,2,23,2,2,2,0,5,2,0,0
889,1,1,1,26,0,0,30,0,0,1,1,5,0,1,1
890,0,3,1,32,0,0,7,1,2,1,1,5,1,0,1

In [20]:
x=d1.drop('survived',axis=1)
x

,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,3,1,22.000000,1,0,7.2500,2,2,1,True,5,2,0,False
1,1,0,38.000000,1,0,71.2833,0,0,2,False,5,0,1,False
2,3,0,26.000000,0,0,7.9250,2,2,2,False,4,2,1,True
3,1,0,35.000000,1,0,53.1000,2,0,2,False,1,2,1,False
4,3,1,35.000000,0,0,8.0500,2,2,1,True,1,2,0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,2,1,27.000000,0,0,13.0000,2,1,1,True,5,2,0,True
887,1,0,19.000000,0,0,30.0000,2,0,2,False,5,2,1,True
888,3,0,29.699118,1,2,23.4500,2,2,2,False,5,2,0,False
889,1,1,26.000000,0,0,30.0000,0,0,1,True,5,0,1,True
890,3,1,32.000000,0,0,7.7500,1,2,1,True,5,1,0,True

In [21]:
y=d1[['survived']]
y

     survived
0           0
1           1
2           1
3           1
4           0
..        ...
886         0
887         1
888         0
889         1
890         0

[889 rows x 1 columns]

In [22]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_scaled=scaler.fit_transform(x)

In [23]:
from sklearn.svm import SVC
model=SVC(kernel='linear')

In [24]:
from sklearn.model_selection import cross_val_score
scores=cross_val_score(model,x_scaled,y,cv=5,scoring='accuracy')

In [25]:
print(scores.mean())

1.0